export enum ReportType {
  'Crypto Dashboard' = 'Crypto Report.trdx',
  'Conference Report' = 'Conference Report.trdx',
  'Dashboard' = 'Dashboard.trdx',
  'Crypto Currency Info' = 'CryptoCurrencyInfo.trdx',
  'Invoice' = 'Invoice.trdx',
  'Swiss QR Bill Report' = 'SwissQRBill.trdx',
  'Barcodes Report' = 'Barcodes Report.trdx',
  'Product Sales' = 'Product Sales.trdx',
  'Employee Sales' = 'Employee Sales Summary.trdx',
  'Product Line Sales' = 'Product Line Sales.trdx',
  'Sales Dashboard' = 'SalesByRegionDashboard.trdx',
  'Report Book' = 'ReportBook.trbp',
  'Crypto Currencies' = 'CryptoCurrencies.trdx',
  'List Bound Report' = 'ListBoundReport.trdx',
  'Product Catalog' = 'Product Catalog.trdx', //parameterValues: {CultureID: "en"}
  'Product Tag Report' = 'Product Tag Report.trdx',
  'Olympic Medals Map' = 'OlympicMedalsByNationalTeams.trdx',
  'Population Density' = 'PopulationDensity.trdx',
}
